services:
  - docker

install:
  - echo "$SSH_HOST_PUBKEY" >> $HOME/.ssh/known_hosts
  - bash install.sh

script:
  - docker-compose run node yarn production
  - docker exec imagery vendor/bin/phpunit

after_failure:
  - cat storage/logs/laravel-*.log
