dist: bionic
language: php
php:
  - 7.3

addons:
  ssh_known_hosts: imagery.bolliger.tech

services:
  - mysql

before_install:
  - openssl aes-256-cbc -K $encrypted_339d88bdb736_key -iv $encrypted_339d88bdb736_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - yes | pecl install imagick
  - yarn install
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS laravel;'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - yarn prod
  - vendor/bin/phpunit

after_failure:
  - cat storage/logs/laravel-*.log

before_deploy:
  - openssl aes-256-cbc -K $encrypted_339d88bdb736_key -iv $encrypted_339d88bdb736_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
