dist: bionic
language: php
php:
  - 7.2
services:
  - mysql
before_install:
  - yes | pecl install imagick
  - yarn install
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS laravel;'
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan migrate --seed
script:
  - vendor/bin/phpunit
  - yarn prod
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
