addons:
  ssh_known_hosts: imagery.bolliger.tech

services:
  - docker

install:
  - bash install.sh
  - sleep 10 # wait until node is up and ready

script:
  - docker exec imagery_node yarn prod
  - docker exec imagery vendor/bin/phpunit

after_failure:
  - cat storage/logs/laravel-*.log

before_deploy:
  - openssl aes-256-cbc -K $encrypted_339d88bdb736_key -iv $encrypted_339d88bdb736_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
