project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /resources/js/locales/en.json
    translation: /resources/js/locales/%two_letters_code%.json
  - source: /resources/lang/en/*.php
    translation: /resources/lang/%two_letters_code%/%original_file_name%
    ignore:
      /resources/lang/en/validation.php
