name: Tests
on: [push]
jobs:
  laravel-tests:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Tests triggered by a ${{ github.event_name }} event to the ${{ github.ref }} branch."
      - uses: actions/checkout@v2

      - name: Install everything
        run: bash install.sh

      - name: Add proprietary files
        env:
          proprietary_key: ${{ secrets.PROPRIETARY_KEY }}
        run: ./.github/scripts/decrypt_proprietary_files.sh

      - name: Run PHPUnit
        run: docker exec imagery vendor/bin/phpunit

      - name: Something failed
        if: ${{ failure() }}
        run: cat storage/logs/laravel-*.log
